@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as StorageInterface
Class StorageManager

package "ExpressLibrary Storage" #F4F6F6{
Class "<<interface>>\nExpressLibraryStorage" as ExpressLibraryStorage
Class JsonExpressLibraryStorage
Class JsonSerializableExpressLibrary
Class JsonAdaptedPerson
Class JsonAdaptedTag
Class JsonAdaptedBook
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> StorageInterface

StorageManager .up.|> StorageInterface
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ExpressLibraryStorage

StorageInterface -left-|> UserPrefsStorage
StorageInterface -right-|> ExpressLibraryStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonExpressLibraryStorage .up.|> ExpressLibraryStorage
JsonExpressLibraryStorage ..> JsonSerializableExpressLibrary
JsonSerializableExpressLibrary --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag
JsonSerializableExpressLibrary --> "*" JsonAdaptedBook

@enduml
